"""empty message

Revision ID: 712d5aabb1a2
Revises: 6d4426ea5ae7
Create Date: 2024-02-21 10:17:48.824021

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '712d5aabb1a2'
down_revision = '6d4426ea5ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
