"""empty message

Revision ID: 72b21ce16aab
Revises: 1c3301020524
Create Date: 2024-02-21 10:15:34.058562

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '72b21ce16aab'
down_revision = '1c3301020524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
