"""empty message

Revision ID: 9dbcb52a24f0
Revises: 3cb1cb77920a
Create Date: 2024-02-21 09:27:16.229953

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9dbcb52a24f0'
down_revision = '3cb1cb77920a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=320),
               existing_nullable=False)

    # ### end Alembic commands ###
